server:
  port: 9800
spring:
  application:
    name: feign-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#eureka hystrix 允许在feign中使用hystrix
feign:
  hystrix:
    enabled: true
