server:
  port: 9200
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: zuul-client
zuul:
  routes:
    api-a:
      serviceId: eureka-client
